name: Deploy to Firebase Hosting on release

on:
  release:
    types: [published]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Extract Firebase Config
        run: 'echo "$FIREBASE" > src/firebase.ts'
        env:
          FIREBASE: ${{secrets.FIREBASE}}
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OTOHIME_WEB }}"
          projectId: otohime-web
          channelId: live
